server:
  port: 0

spring:
  application:
    name: websocket-service

eureka:
  client:
    service-url:
      defaultZone: ${DEFAULT_ZONE}
  instance:
    prefer-ip-address: true

logging:
  level:
    com.momnect.websocketservice: DEBUG
    org.springframework.web.socket: DEBUG
