apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: momnect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: junga970/chat-service:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: app-secret
