apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service
  namespace: momnect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-service
  template:
    metadata:
      labels:
        app: file-service
    spec:
      containers:
        - name: file-service
          image: junga970/file-service:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: app-secret
