apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-service
  namespace: momnect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket-service
  template:
    metadata:
      labels:
        app: websocket-service
    spec:
      containers:
        - name: websocket-service
          image: junga970/websocket-service:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: app-secret
