server:
  port: 0
  forward-headers-strategy: framework

spring:
  application:
    name: review-service
  jpa:
    hibernate:
      ddl-auto: update       # 운영 시엔 update/validate 권장
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  ai:
    openai:
      api-key: ${OPEN_AI_KEY}
      chat:
        options:
          model: gpt-3.5-turbo

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DEFAULT_ZONE}

# 커스텀 OpenAI 설정
openai:
  model: gpt-3.5-turbo
  max_tokens: 200
  temperature: 0.7

springdoc:
  packages-to-scan: com.momnect.reviewservice
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
